### PR TITLE
BUPH-75 | Support fully qualified traits

### PR DESCRIPTION
**Pull request by jpmarcotte**
Only applies to V1.

### CODE REVIEW

**Review by arielallon — APPROVED** [review]
seems fine to me but i'm also not certain what to be looking for.

**Comment by jpmarcotte** [comment]
> i'm also not certain what to be looking for.

I just added autolinks, but it doesn't seem to have taken affect for this already existing PR. This should sum it up: https://55places.atlassian.net/browse/BUPH-75

**Review by mucha55 — APPROVED** [review]
That's an interesting test setup 😅

**Comment by jpmarcotte** [comment]
> That's an interesting test setup 😅

Yeah, it felt like full integration tests were more appropriate than trying to just test specifics of the internals with something like PHPUnit, especially because we were planning on reworking a bunch of the internals.

**Pull request merged**
